// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxwr7My3SnEoWqZqYzM0t-kHn5kNfKT8',
    appId: '1:190142885925:web:702a40bb7c1af2a21e8fcc',
    messagingSenderId: '190142885925',
    projectId: 'velai-app-ce984',
    authDomain: 'velai-app-ce984.firebaseapp.com',
    storageBucket: 'velai-app-ce984.firebasestorage.app',
    measurementId: 'G-KQFP4P8Q4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqm9LH4SDCW72nLKU0sb5DclWuMtO_E9M',
    appId: '1:190142885925:android:d3239dcc06ee80f01e8fcc',
    messagingSenderId: '190142885925',
    projectId: 'velai-app-ce984',
    storageBucket: 'velai-app-ce984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUkucOBBTPgswp771nOt0UNhxPNBZXVI',
    appId: '1:190142885925:ios:109d8528250b16921e8fcc',
    messagingSenderId: '190142885925',
    projectId: 'velai-app-ce984',
    storageBucket: 'velai-app-ce984.firebasestorage.app',
    androidClientId: '190142885925-cr09cghm48gr57r5gjsn17ra3k5pnmpk.apps.googleusercontent.com',
    iosClientId: '190142885925-rdrat9rsl13i288jee22jriu44luiqs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.velai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLUkucOBBTPgswp771nOt0UNhxPNBZXVI',
    appId: '1:190142885925:ios:109d8528250b16921e8fcc',
    messagingSenderId: '190142885925',
    projectId: 'velai-app-ce984',
    storageBucket: 'velai-app-ce984.firebasestorage.app',
    androidClientId: '190142885925-cr09cghm48gr57r5gjsn17ra3k5pnmpk.apps.googleusercontent.com',
    iosClientId: '190142885925-rdrat9rsl13i288jee22jriu44luiqs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.velai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFxwr7My3SnEoWqZqYzM0t-kHn5kNfKT8',
    appId: '1:190142885925:web:498a6f230bb01c481e8fcc',
    messagingSenderId: '190142885925',
    projectId: 'velai-app-ce984',
    authDomain: 'velai-app-ce984.firebaseapp.com',
    storageBucket: 'velai-app-ce984.firebasestorage.app',
    measurementId: 'G-K62GFT7V6B',
  );
}
